site_name: virtual-spot-weld
nav:
    - Home: index.md
    - "User Guide - Usage": userguide_usage.md
    - "User Guide - Code": userguide_code.md
    - API: apireference.md
    - About: about.md
    
theme: 
    name: 'material'
    logo: assets/logo.png
    favicon: assets/favicon.png

markdown_extensions:
  - attr_list
  - md_in_html